# Use root/example as user/password credentials
version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      AUTH: "yes"
      MONGODB_ADMIN_USER: admin
      MONGODB_ADMIN_PASS: admin123
      MONGODB_APPLICATION_DATABASE: gonode03
      MONGODB_APPLICATION_USER: docker
      MONGODB_APPLICATION_PASS: docker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
